version: '3.8'

services:
  nextjs:
    image: chinoel/personalstudy:latest
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - study-net

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - study-net

networks:
  study-net:
    external: true

volumes:
  mysql-data:
