version: '3.8'

services:
  nextjs:
    image: chinoel/personalstudy:latest
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - study-net

networks:
  study-net:
    external: true
