name: Personal Study Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chinoel/personalstudy:latest .

      - name: Push Docker Image
        run: |
          docker push chinoel/personalstudy:latest

      - name: Trigger Server Deployment via Docker Compose
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Ensure Docker Compose uses the latest image
          docker-compose -f /path/to/your/docker-compose.yml down || true
          docker-compose -f /path/to/your/docker-compose.yml up -d
