name: Personal Study Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chinoel/personalstudy:latest .

      - name: Push Docker Image
        run: |
          docker push chinoel/personalstudy:latest

      - name: Deploy to Server (via SSH)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker pull chinoel/personalstudy:latest
          docker stop personalstudy || true
          docker rm personalstudy || true
          docker run -d --name personalstudy \
          -e JWT_SECRET=$JWT_SECRET \
          -e DATABASE_URL=$DATABASE_URL \
          -p 3000:3000 \
          chinoel/personalstudy:latest