name: Personal Study Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chinoel/personalstudy:latest .

      - name: Push Docker Image
        run: |
          docker push chinoel/personalstudy:latest

      - name: SSH into server and deploy (with docker-compose)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            # Pull the latest Docker image
            docker pull chinoel/personalstudy:latest

            # Ensure MySQL is connected to the correct network
            docker network connect study-net selfStudy || true

            # Deploy the new Docker container using Docker Compose
            docker-compose down || true
            docker-compose up -d

            # Clean up old containers
            docker container prune -f
          EOF
